### ISSUE TITLE
SDK can crash from time to time when using NextJS

### ISSUE THREAD

**Issue by thecoorum** [Telegram-Mini-Apps/tma.js#210] opened 2023-12-15 10:16 UTC
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

When using `@tma.js/sdk-react` with NextJS an issue with SDK crashing with `undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')` can appear from time to time

## To Reproduce

1. Mount the SDK provider with the following code
```tsx
"use client";

import { useState, useEffect, useMemo } from "react";

import { useSDKContext } from "@tma.js/sdk-react";

export const ComponentsProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [render, setRender] = useState(false);
  const { loading, error } = useSDKContext();

  useEffect(() => {
    setRender(true);
  }, []);

  const errorMessage = useMemo<null | string>(() => {
    if (!error) {
      return null;
    }

    return error instanceof Error ? error.message : "Unknown error";
  }, [error]);

  if (!render) return null;

  if (error) {
    setTimeout(() => {
      throw new Error(`SDK error: ${errorMessage}`);
    });

    return <Alert />;
  }

  if (loading) {
    return <Loading />;
  }

  return children;
};
```
2. Create several pages linked to each other with `useRouter` from `next/navigation`
3. Navigate between pages and see the issue from time to time

**Comment by heyqbnk** [comment] 2023-12-15 18:42
Yeah, no problem. Just pm whenever you are free.

Until then, please, check out the updated [Next JS template](https://github.com/Telegram-Mini-Apps/nextjs-template)

**Comment by heyqbnk** [comment] 2023-12-19 08:26
We dig into the problem and could not really find out why the problem sometimes occurs. We were getting it absolutely randomly and extremely rarely. The problem is, for some reason Next server calls function wrapped in `useEffect`. To be more accurate, it calls the SDK init which leads to error.

There is only 1 assumption - Vercel did not shutdown the broken server and sometimes directs the request to it.

@thecoorum Please, let me know if you find the solution and why this problem occurs. Until then, I am closing the issue assuming, the problem is not in the SDK.

**Closed by heyqbnk** 2023-12-19 08:26 UTC
Labels: bug

**Comment by thecoorum** [comment] 2023-12-20 12:21
I suspect the source of the issue is the middleware with rewrites to support multi-tenancy. Can see in the logs that it does rewrite to the same URL twice, maybe in the process the init params are lost or something like that. So, that's definitely not the SDK issue
